export enum ActionTypes {
  ARTIST_GET_CONTENT = 'ARTIST/GET_CONTENT',
  GENRE_GET_CONTENT = 'GENRE/GET_CONTENT',
  SELECTION_GET_CONTENT = 'SELECTION/GET_CONTENT',
  SERIES_GET_CONTENT = 'SERIES/GET_CONTENT',
  WORK_GET_CONTENT = 'WORK/GET_CONTENT',
  YEAR_BEST_GET_CONTENT = 'YEAR_BEST/GET_CONTENT',
}
