export enum ActionTypes {
  GET_ARTIST = 'GET_ARTIST',
  GET_ARTISTS = 'GET_ARTISTS',

  GET_GENRE = 'GET_GENRE',
  GET_GENRES = 'GET_GENRES',

  GET_SELECTION = 'GET_SELECTION',
  GET_SELECTIONS = 'GET_SELECTIONS',

  GET_SERIES = 'GET_SERIES',
  GET_SERIES_LIST = 'GET_SERIES_LIST',

  GET_WORK = 'GET_WORK',
  GET_WORKS = 'GET_WORKS',

  GET_YEAR_BEST = 'GET_YEAR_BEST',
  GET_YEAR_BESTS = 'GET_YEAR_BESTS',
}
